version: "3.8"
services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.4
    container_name: mqtt_broker
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "1883:1883" # Port pentru MQTT
      - "9001:9001" # Port pentru WebSocket (opțional, pentru debugging)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - broker_network

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8086:8086"  # InfluxDB UI and API
    volumes:
      - ./influxdb_data:/var/lib/influxdb2  # Bind mount to a specific folder
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_ORG=vpt.srl
      - INFLUXDB_BUCKET=iot_data
      - INFLUXD_LOG_LEVEL=debug  # Set the log level to debu
      - INFLUX_TOKEN=5UOXmCh_Es_Qnfsaw-zYhtjuOwRykjTpr2Vdf90p_jA26bco7rt3VRYgbz4V-MDW82YLK-9SrW_yImbhNrVLWg==
    networks:
      - database_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"  # Expose Grafana on port 80
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSCD2024
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards.yml
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources.yml
    depends_on:
      - influxdb
    networks:
      - database_network

  # loki:
  #   image: grafana/loki
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "3100:3100"

  adaptor:
    image: cosmf24/adaptor:latest
    build:
      context: ./adaptor
    depends_on:
      - mqtt-broker
      - influxdb
    networks:
      - broker_network
      - database_network

  message_publisher:
    image: cosmf24/message_publisher:latest
    build:
      context: ./message_publisher
    depends_on:
      - mqtt-broker
    networks:
      - broker_network

  # message_publisher1:
  #   image: cosmf24/message_publisher1:latest
  #   build:
  #     context: ./message_publisher1
  #   depends_on:
  #     - mqtt-broker
  #   networks:
  #     - broker_network


volumes:
  mosquitto_data:
  mosquitto_logs:
  influxdb_data:
  grafana_data:

networks:
  broker_network:
    driver: overlay
    attachable: true
  database_network:
    driver: overlay
    attachable: true
